---
title: ""
page-layout: full
---

Henry O. & **Ferry, M.** (2025). What Does My IITian Tag Actually Mean? The Relationship between Academic Titles and Job Positions: The Case of Students at an Indian Institute of Technology (IIT). In V. Caru (Ed.), *Engineers and Society in India: From circa 1850 to Present Times* (pp. 139–178). Oxford University Press.  

::: {.content-visible when-profile="english"}
[{{< iconify ph book-duotone >}}Publisher's website](https://doi.org/10.1093/9780198935940.003.0006)
:::

::: {.content-visible when-profile="french"}
[{{< iconify ph book-duotone >}}Site de l'éditeur](https://doi.org/10.1093/9780198935940.003.0006)
:::

------------------------------------------------------------------------


**Ferry, M.**, & Ichou, M. (2024). The role of migration for intergenerational mobility. In E. Kilpi-Jakonen, J. Blanden, J. Erola, & L. Macmillan (Eds.), *Research Handbook on Intergenerational Inequality* (pp. 249–263). Edward Elgar Publishing. 

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} Pre-print](chapters/ferry-ichou-2024/Ferry_Ichou_2024_ChapterIntergMobilityMigration.pdf) [{{< iconify ph book-duotone >}}Publisher's website](https://doi.org/10.4337/9781800888265.00027)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} Prépublication](chapters/ferry-ichou-2024/Ferry_Ichou_2024_ChapterIntergMobilityMigration.pdf) [{{< iconify ph book-duotone >}}Site de l'éditeur](https://doi.org/10.4337/9781800888265.00027)
:::

------------------------------------------------------------------------

**Ferry, M.** (2023). Vegetarianism and Non-Vegetarian Consumption in India, in: Guilmoto, C.Z. (Ed.), *Atlas of Gender and Health Inequalities in India, Demographic Transformation and Socio-Economic Development*. Springer Nature Switzerland, Cham, pp. 29–39.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} Main map](chapters/ferry-map-veg-2023/VegetarianismMap.png) [{{< iconify ph book-duotone >}}Publisher's website](https://doi.org/10.1007/978-3-031-47847-5_3)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} Carte principale](chapters/ferry-map-veg-2023/VegetarianismMap.png) [{{< iconify ph book-duotone >}}Site de l'éditeur](https://doi.org/10.1007/978-3-031-47847-5_3)
:::

------------------------------------------------------------------------

**Ferry, M.** (2024). Social Honour. In S. S. Jodhka & B. Rehbein (Eds.), *Global Handbook of Inequality*. Cham: Springer International Publishing (living reference work entry).

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} Pre-print](chapters/ferry-2023/Preprint-ferry-2023.pdf) [{{< iconify ph book-duotone >}}Publisher's website](https://doi.org/10.1007/978-3-030-97417-6_20-1)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} Prépublication](chapters/ferry-2023/Preprint-ferry-2023.pdf) [{{< iconify ph book-duotone >}}Site de l'éditeur](https://doi.org/10.1007/978-3-030-97417-6_20-1)
:::

------------------------------------------------------------------------

Bruckert, M., & **Ferry, M.** (2023). Changing Food Habits in Contemporary India: Discourses and Practices among the Middle Classes. In K. A. Jacobsen (Ed.), *Routledge Handbook of Contemporary India* (2nd ed.). Routledge.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} Pre-print](chapters/bruckert-ferry-2023/Bruckert_Ferry_2023.pdf) [{{< iconify ph book-duotone >}}Publisher's website](https://www.taylorfrancis.com/chapters/edit/10.4324/9781003278436-42/changing-food-habits-contemporary-india-micha%C3%ABl-bruckert-mathieu-ferry)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} Prépublication](chapters/bruckert-ferry-2023/Bruckert_Ferry_2023.pdf) [{{< iconify ph book-duotone >}}Site de l'éditeur](https://www.taylorfrancis.com/chapters/edit/10.4324/9781003278436-42/changing-food-habits-contemporary-india-micha%C3%ABl-bruckert-mathieu-ferry)
:::

------------------------------------------------------------------------

Henry, O., & **Ferry, M.** (2022). Assignation statutaire et valeur sociale des diplômes Le devenir scolaire et professionnel des élèves ­d'un Institut indien de technologie au prisme des catégories de réservation. In C. Gadéa & R. Lardinois (Eds.), *Les Mondes de l'ingénieur en Inde (xixe-xxie siècle)* (Vol. 24, pp. 147--171). Paris: Classiques Garnier.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} Pre-print](https://hal.science/hal-03922691/document) [{{< iconify ph book-duotone >}}Publisher's website](https://classiques-garnier.com/les-mondes-de-l-ingenieur-en-inde-xixe-xxie-siecle-assignation-statutaire-et-valeur-sociale-des-diplomes.html)

*Note: this chapter synthesizes two of our research outputs on caste inequality in higher education (in the engineering field) in India, one of which is already available in English in* [SAMAJ](https://doi.org/10.4000/samaj.4291) *and the other coming out soon as a book chapter at OUP.*
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} Prépublication](https://hal.science/hal-03922691/document) [{{< iconify ph book-duotone >}}Site de l'éditeur](https://classiques-garnier.com/les-mondes-de-l-ingenieur-en-inde-xixe-xxie-siecle-assignation-statutaire-et-valeur-sociale-des-diplomes.html)
:::

------------------------------------------------------------------------

Al Dahdah, M., **Ferry, M.**, Guérin, I., & Venkatasubramanian, G. (2021). India in COVID-19: A Tragedy Foretold. In T. J. Sugrue & C. Zaloom (Eds.), *The long year: a 2020 reader*. New York: Columbia University Press.

::: {.content-visible when-profile="english"}
[{{< iconify ph book-duotone >}}Publisher's website](https://www.jstor.org/stable/10.7312/sugr20452?turn_away=true)

*Note: this chapter is a slightly edited version of our text published on* [Books&Ideas](https://laviedesidees.fr/The-Covid-19-Crisis-in-India)*.*
:::

::: {.content-visible when-profile="french"}
[{{< iconify ph book-duotone >}}Chapitre sur JSTOR](https://www.jstor.org/stable/10.7312/sugr20452?turn_away=true)

*Note: ce chapitre est une version éditée d'un essai publié sur* [La Vie des Idées](https://laviedesidees.fr/L-Inde-face-a-la-crise-du-Covid-19) *(initialement publié en anglais dans* [Books&Ideas](https://laviedesidees.fr/The-Covid-19-Crisis-in-India)*)*.
:::

------------------------------------------------------------------------

Naudet, J., Allorant, A., & **Ferry, M.** (2019). Heirs, Corporate Aristocrats, and 'Meritocrats': The Social Space of Top CEOs and Chairpersons in India. In S. S. Jodhka & J. Naudet (Eds.), *Mapping the Elite: Power, Privilege, and Inequality* (pp. 70--114). Oxford University Press.

::: {.content-visible when-profile="english"}
[{{< iconify ph book-duotone >}}Publisher's website](https://doi.org/10.1093/oso/9780199491070.003.0003)

*Note: this chapter is a slightly edited version of our journal article published in the* [Socio-Economic Review](https://doi.org/10.1093/ser/mwx035) *(available here as a [PDF](articles/naudet-allorant-ferry-2018/ser.pdf)).*
:::

::: {.content-visible when-profile="french"}
[{{< iconify ph book-duotone >}}Site de l'éditeur](https://doi.org/10.1093/oso/9780199491070.003.0003)

*Note: ce chapitre est une version légèrement remaniée d'un article publié dans la* [Socio-Economic Review](https://doi.org/10.1093/ser/mwx035) *(disponible ici en [PDF](articles/naudet-allorant-ferry-2018/ser.pdf)).*
:::
