project:
  title: "Mathieu Ferry"
  output-dir: ./docs/fr

website:
  navbar:
    background: "#A3133D"
    left:
      - href: index.qmd
        text: Présentation
      - href: cv/index.qmd        
        text: CV
      - icon: book
        href: publications/index.qmd
        text: Publications
      - href: teaching/index.qmd
        text: "{{< iconify mdi teacher >}} Enseignements"
      - icon: pencil
        href: posts.qmd
        text: Blog
    right:
      - href: ../fr
        text: Français
      - href: ../
        text: English

lang: fr

format:
  html:
    theme: united
    mainfont: arial
    fontsize: 1.5rem
    linkcolor: "#A3133D"
    css: styles.css
    toc: true

