project:
  type: website

profile:
  default: english
  group: [english, french]

website: 
  favicon: image/icon.png
  body-footer: |
    <script defer src="https://cloud.umami.is/script.js" data-website-id="2cc75ac6-21f8-41be-9c15-c3e06cbadefa"></script>




  
