project:
  type: website

profile:
  default: english
  group: [english, french]

website: 
  favicon: image/icon.png
  body-footer: |
    <script defer data-domain="mathieuferry.github.io" src="https://plausible.io/js/script.js"></script>




  
