---
title: ""
page-layout: full
---

::: {.content-visible when-profile="english"}
# Teaching {{< iconify mdi teacher >}}

In the course of teaching quantitative methods for the social sciences, I have started to compile some course materials here.

## Data Analysis

The Data Analysis course is designed for 3rd year undergraduate students in the "Mathematics for social sciences" and in the sociology tracks. It offers an introduction to Geometric Data Analysis: the lecture combines method presentations with real-world social science applications, and the tutorials focus on applying these methods to real datasets using the R software.

You will find some of the guided exercise solutions [here](https://mathieuferry.github.io/AnalyseDesDonnees/).

## Textual Analysis

I participated in the [Pondicherry Social Science Winter School](https://www.ifpindia.org/ifp-in-spotlight/apply-now-digital-society-social-sciences-winter-school-november-13-17-2023-Ifp/) in November 2023, where I co-hosted the "Computational and Mixed Methods" workshop. During the workshop, I presented Max Reinert's textual analysis method, which is now available in the "rainette" R package developed by Julien Barnier. This method was applied to data collected from matrimonial advertisements on an Indian website.

You can access the tutorials for the workshop [here](https://mathieuferry.github.io/PondicherryWorkshop/).

## Textual Analysis with Mendak

To introduce text analysis in a "point-and-click" mode, one can use the Mendak application ([here](https://analytics.huma-num.fr/Mathieu.Ferry/mendak/), or better, [here](https://shiny.ens-paris-saclay.fr/app/mendak)).

You can access a (brief) tutorial in English [here](https://mathieuferry.github.io/Tutorials-for-Mendak/TutorialEN.html).

## Teaching stats for social scientists in R

I gathered the teaching material used for teaching R for social scientists for a workshop with PhD students from the Sociology and Political Science Graduate School of Université Paris-Saclay (June 2025). The tutorials cover univariate, bivariate, MCA, textual analysis and a few functions that render data management easier in R.

You can access the tutorials (in French) for the workshop [here](https://mathieuferry.github.io/FormationR/).

## Social Sciences Mixed Methods National Research Project

Along with Marine Al Dahdah, Louise Caron, Andrew McDowell, and Priyadarshani Premarathne, I conduct a collaborative, year-long [research-cum-teaching program](https://www.ifpindia.org/projects/social-sciences-mixed-methods-national-research-project/) in Sri Lanka in 2025-2026. The program involves 40 students from 10 universities and 10 statisticians from the Department of Census and Statistics. We aim to strengthen mixed-methods research and the project studies project access to health, education, and basic services. The project is financially supported by the French Ministry of Foreign Affairs. As part of this program, I deliver training in [Statistics with R](https://mathieuferry.github.io/SoMixQuantTutorial/).

:::

::: {.content-visible when-profile="french"}
# Enseignements {{< iconify mdi teacher >}}

Dans le cadre des enseignements de méthodes quantitatives pour les sciences sociales, j'ai commencé à rassembler ici quelques supports de cours.

## Analyse des données

Le cours d'Analyse des données s'adresse à des étudiants de L3 "Mathématiques et Informatique Appliquées aux Sciences Humaines et Sociales" (MIASHS) et constitue également un électif pour les étudiants de L3 en sociologie. Il propose une introduction à l'Analyse Géométrique des Données : le cours magistral articule présentation des méthodes et illustrations en sciences sociales, et les travaux dirigés sont consacrés à l'application des méthodes sur des jeux de données réelles à l'aide du logiciel R.

On pourra retrouver quelques corrigés des travaux dirigés [ici](https://mathieuferry.github.io/AnalyseDesDonnees/).

## Séminaire d'Analyse Textuelle

J'ai participé à la [Winter School de Pondicherry](https://www.ifpindia.org/ifp-in-spotlight/apply-now-digital-society-social-sciences-winter-school-november-13-17-2023-Ifp/) en novembre 2023, en co-animant le workshop "Computational and mixed methods". J'y ai présenté la méthode d'analyse textuelle développée par Max Reinert, maintenant disponible dans R grâce au package R "rainette" dévelopé par Julien Barnier. J'illustre cette d'exploration textuelle à partir de données issues d'une aspiration d'annonces matrimoniales d'un site internet indien.

Les tutoriels du workshop sont à retrouver [ici](https://mathieuferry.github.io/PondicherryWorkshop/).

## L'analyse textuelle avec EuroDecodeur et Mendak

Pour faire découvrir l'analyse textuelle en mode "clic-bouton", on peut mobiliser l'application Mendak ([ici](https://analytics.huma-num.fr/Mathieu.Ferry/mendak/) ou mieux, [ici](https://shiny.ens-paris-saclay.fr/app/mendak)). On pourra suivre un tutoriel de création d'un corpus d'articles avec Europresse, qui est ensuite utilisable dans Mendak (ou ailleurs) en suivant les consignes de ce [petit tuto](https://mathieuferry.github.io/FormationR/corpus.html) et en utilisant EuroDecodeur ([ici](https://analytics.huma-num.fr/Mathieu.Ferry/EuroDecodeur/) ou [ici](https://mathieufer.shinyapps.io/europressedecodeur/)).

Un tutoriel de présentation des fonctionnalités de Mendak est disponible [ici](https://mathieuferry.github.io/Tutorials-for-Mendak/TutorielFR.html).

## R pour les sciences sociales quantitatives

J’ai rassemblé les tutoriels utilisés pour enseigner R pour les sciences sociales dans le cadre d’un atelier destiné aux doctorant·e·s de l’École doctorale de sociologie et de science politique de l’Université Paris-Saclay (juin 2025). Les tutos couvrent l’analyse univariée, bivariée, l’ACM, l’analyse textuelle, ainsi que quelques fonctions facilitant la gestion des données sous R.

Les tutoriels du workshop sont à retrouver [ici](https://mathieuferry.github.io/FormationR/).

## Social Sciences Mixed Methods National Research Project

Avec Marine Al Dahdah, Louise Caron, Andrew McDowell et Priyadarshani Premarathne, je mène un [programme collaboratif de formation-recherche](https://www.ifpindia.org/projects/social-sciences-mixed-methods-national-research-project/) d’une durée d’un an au Sri Lanka en 2025-2026. Le programme réunit 40 étudiant·e·s issu·e·s de 10 universités ainsi que 10 statisticien·ne·s du Department of Census and Statistics. Il vise à renforcer les compétences en recherche en méthodes mixtes et porte sur l’accès aux services de santé, d’éducation et aux services de base. Le projet est soutenu financièrement par le ministère français des Affaires étrangères. Dans le cadre de ce programme, j’assure une formation en [statistiques avec R](https://mathieuferry.github.io/SoMixQuantTutorial/).
:::
