---
title: ""
page-layout: full
---

::: {.content-visible when-profile="french"}
**Ferry M.**, Bouchet-Valat M., Drouhot L. G., Ichou M., Obućina O. (2025). Shades of *Égalité*: Educational Mobility and Ethnoracial Hierarchy Over Three Generations in France, *American Sociological Review*, *First published online 2025-11-22*.

[{{< iconify icons8 pdf >}} PDF](https://archined.ined.fr/view/6exMv5oBJC0okJu_lbcb) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1177/00031224251391760)
:::

::: {.content-visible when-profile="english"}
**Ferry M.**, Bouchet-Valat M., Drouhot L. G., Ichou M., Obućina O. (2025). Shades of *Égalité*: Educational Mobility and Ethnoracial Hierarchy Over Three Generations in France, *American Sociological Review*, *First published online 2025-11-22*.

[{{< iconify icons8 pdf >}} PDF](https://archined.ined.fr/view/6exMv5oBJC0okJu_lbcb) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1177/00031224251391760)
:::

------------------------------------------------------------------------


::: {.content-visible when-profile="french"}
Lavest C., **Ferry M.**, Ichou M., Präg P. (2025). Who do they think you are? Inconsistencies in self- and proxy-reports of education within families, *Social Science Research*, *132*.

[{{< iconify icons8 pdf >}} PDF](https://osf.io/b2qsu_v2) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1016/j.ssresearch.2025.103225)
:::

::: {.content-visible when-profile="english"}
Lavest C., **Ferry M.**, Ichou M., Präg P. (2025). Who do they think you are? Inconsistencies in self- and proxy-reports of education within families, *Social Science Research*, *132*.

[{{< iconify icons8 pdf >}} PDF](https://osf.io/b2qsu_v2) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1016/j.ssresearch.2025.103225)
:::

------------------------------------------------------------------------

::: {.content-visible when-profile="french"}
Ichou M., **Ferry M.** (2025). Immigration et mobilité sociale. Revue de la littérature internationale sur les tendances observées et leurs mécanismes explicatifs, *L'Année Sociologique*, *75*.

[{{< iconify icons8 pdf >}} PDF](articles/ichou-ferry-2025/vacceptee.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.3917/anso.251.0015)
:::

::: {.content-visible when-profile="english"}
Ichou M., **Ferry M.** (2025). Immigration and Social Mobility. A Review of the International Literature on Observed Trends and their Explanatory Mechanisms, *L'Année Sociologique*, *75*.

[{{< iconify icons8 pdf >}} PDF](articles/ichou-ferry-2025/vacceptee.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.3917/anso.251.0015)
:::

------------------------------------------------------------------------

::: {.content-visible when-profile="french"}
**Ferry M.** (2025). Le prix du végétarisme Légitimité et autonomie culturelle de la caste en Inde contemporaine, *Bulletin de Méthodologie Sociologique*, Online First.

[{{< iconify icons8 pdf >}} PDF](articles/ferry-2025/ferry-2025_vegetarisme.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1177/07591063251317058)
:::

::: {.content-visible when-profile="english"}
**Ferry M.** (2025). At the Cost of Vegetarianism. Caste legitimacy and cultural autonomy in contemporary India, *Bulletin of Sociological Methodology*, Online First.

[{{< iconify icons8 pdf >}} PDF (in French)](articles/ferry-2025/ferry-2025_vegetarisme.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1177/07591063251317058)
:::

------------------------------------------------------------------------

Weber R., **Ferry, M.,** Ichou M. (2024). Which Degree for Which Occupation? Vertical and Horizontal Mismatch Among Immigrants, Their Children, and Grandchildren in France. *Demography*, 11670148.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} PDF](https://read.dukeupress.edu/demography/article-pdf/doi/10.1215/00703370-11670148/2172062/11670148.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1215/00703370-11670148)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} PDF](https://read.dukeupress.edu/demography/article-pdf/doi/10.1215/00703370-11670148/2172062/11670148.pdf) [{{< iconify ph newspaper-light >}} Revue](https://doi.org/10.1215/00703370-11670148)
:::

------------------------------------------------------------------------

::: {.content-visible when-profile="french"}
**Ferry M.** (2024). Le gastro-nationalisme de la vache en Inde. L’instrumentalisation d’un symbole religieux dans le renforcement du sentiment national hindou et la stigmatisation des musulmans, *Critique internationale*, *103* (2), 11‑-38.

[{{< iconify ph newspaper-light >}} DOI](https://www.cairn.info/revue-critique-internationale-2024-2-page-11.htm)
:::

::: {.content-visible when-profile="english"}
**Ferry M.** (2024). Cow gastronationalism in India: The instrumentalization of a religious symbol in reinforcing Hindu national sentiment and stigmatizing Muslims, *Critique internationale*, *103* (2), 11‑-38.

[{{< iconify ph newspaper-light >}} Revue](https://www.cairn-int.info/journal-critique-internationale-2024-2-page-11.htm)
:::

------------------------------------------------------------------------

**Ferry, M.** (2022). Where Does Ascribed Privilege Get You in? Structural and Net Effects of Caste and Religious Belonging in India. *Sociology*, *56*(6), 1176--1199.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} Pre-print](articles/ferry-2022/Classmob_sociology2022_vaccepted.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1177/00380385221083890)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} Prépublication](articles/ferry-2022/Classmob_sociology2022_vaccepted.pdf) [{{< iconify ph newspaper-light >}} Revue](https://doi.org/10.1177/00380385221083890)
:::

------------------------------------------------------------------------

**Ferry, M.** (2020). What's India's Beef with Meat? Hindu Orthopraxis and Food Transition in India Since the 1980. *Sociological Forum*, *35*(2), 511--534.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} PDF](articles/ferry-2020/socf.12592.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1111/socf.12592)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} PDF](articles/ferry-2020/socf.12592.pdf) [{{< iconify ph newspaper-light >}} Revue](https://doi.org/10.1111/socf.12592)
:::

------------------------------------------------------------------------

Naudet, J., Allorant, A., & **Ferry, M.** (2018). Heirs, corporate aristocrats and 'Meritocrats': the social space of top CEOs and Chairmen in India. *Socio-Economic Review*, *16*(2), 307--339.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} PDF](articles/naudet-allorant-ferry-2018/ser.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.1093/ser/mwx035)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} PDF](articles/naudet-allorant-ferry-2018/ser.pdf) [{{< iconify ph newspaper-light >}} Revue](https://doi.org/10.1093/ser/mwx035) [{{< iconify ph newspaper-light >}} Version française (*Entreprises et Histoire*)](articles/naudet-allorant-ferry-2018/EH_090_0088-2-19.pdf.pdf)
:::

------------------------------------------------------------------------

**Ferry, M.**, Naudet, J., & Roueff, O. (2018). Seeking the Indian social space. A multidimensional portrait of the stratifications of Indian society. *South Asia Multidisciplinary Academic Journal*.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} PDF](articles/ferry-naudet-roueff-2018/samaj-4462.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.4000/samaj.4462)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} PDF](articles/ferry-naudet-roueff-2018/samaj-4462.pdf) [{{< iconify ph newspaper-light >}} Revue](https://doi.org/10.4000/samaj.4462)
:::

------------------------------------------------------------------------

Henry, O., & **Ferry, M.** (2017). When Cracking the JEE is not Enough. *South Asia Multidisciplinary Academic Journal*, *15*.

::: {.content-visible when-profile="english"}
[{{< iconify icons8 pdf >}} PDF](articles/henry-ferry-2017/samaj-4291.pdf) [{{< iconify ph newspaper-light >}} DOI](https://doi.org/10.4000/samaj.4291)
:::

::: {.content-visible when-profile="french"}
[{{< iconify icons8 pdf >}} PDF](articles/henry-ferry-2017/samaj-4291.pdf) [{{< iconify ph newspaper-light >}} Revue](https://doi.org/10.4000/samaj.4291)
:::
