---
title: ""
page-layout: full
---

::: {.content-visible when-profile="english"}
Lavest C., **Ferry M.**, Ichou M., Präg P., 2024. Who Do They Think You Are? Inconsistencies in Self-and Proxy-Reports of Education Within Families. *SocArXiv Papers*.

[{{< iconify gg website >}} Website](https://osf.io/preprints/socarxiv/b2qsu)

*The following three working papers compile several analyses to which I have contributed, drawing on the "Trajectoires & Origines 2" (TeO2) survey focused on immigrants and immigrants' descendants in metropolitan France. These papers are intended for publication as chapters in a book project that is presently under review:*

**Ferry, M.**, Tanneau, P., Simon, P., 2023. De la mixité des ascendances à l’hybridation des généalogies. *Documents de travail*, n°288, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://doi.org/10.48756/ined-dt-288.0124)

**Ferry, M.**, Simon, P., 2023. Les rapports aux origines : des identités mouvantes confrontées aux assignations. *Documents de travail*, n°287, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://archined.ined.fr/view/d5wI84wB-5e4nGnw6Kgw)

Caron, L., **Ferry, M.**, Ichou, M., 2023. Diversité sociale des immigré·es et de leurs enfants : positions et mobilité intergénérationnelle. *Documents de travail,* n°282, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://doi.org/10.48756/ined-dt-282.1123)

------------------------------------------------------------------------

Weber, R., **Ferry, M.**, & Ichou, M. (2023). Which Degree for Which Occupation? Vertical and Horizontal Mismatch Among Immigrants, Their Children, and Grandchildren in France. *Documents de travail Ined,* 278.

[{{< iconify icons8 pdf >}} PDF](https://archined.ined.fr/download/publication/E5OPhosBhU4QGwadVTE1/36fe6e5514cb19419c2bdf1cbc68b9d51699446278245.pdf) [{{< iconify gg website >}} Website](https://archined.ined.fr/view/E5OPhosBhU4QGwadVTE1)

------------------------------------------------------------------------

**Ferry, M.**, & Subtil, J. (2023). Digitized Matchmaking. Marriage-making strategies of the New Middle Class through online matrimonial advertisements in India. *CSH-IFP Working Papers,* 19.

[{{< iconify icons8 pdf >}} PDF](https://mathieuferry.github.io/PondicherryWorkshop/material/wp/Digitized%20Matchmaking_WP19.pdf)

------------------------------------------------------------------------

**Ferry, M.** (2019). Caste links. Quantifying social identities using open-ended questions. *Sciences Po OSC Papers,* 1.

[{{< iconify icons8 pdf >}} PDF](https://www.sciencespo.fr/osc/sites/sciencespo.fr.osc/files/OP_2019-1-EN-def.pdf) [{{< iconify gg website >}} Website](https://www.sciencespo.fr/osc/fr/node/2089.html)
:::

::: {.content-visible when-profile="french"}
Lavest C., **Ferry M.**, Ichou M., Präg P., 2024. Who Do They Think You Are? Inconsistencies in Self-and Proxy-Reports of Education Within Families. *SocArXiv Papers*.

[{{< iconify gg website >}} Website](https://osf.io/preprints/socarxiv/b2qsu)

*Les trois documents de travail suivants rassemblent plusieurs analyses auxquelles j'ai contribué, en se basant sur l'enquête "Trajectoires & Origines 2" (TeO2) portant sur les immigrants et leurs descendants en France métropolitaine. Ils sont destinés à être publiés en tant que chapitres d'un ouvrage actuellement en cours de révision :*

**Ferry, M.**, Tanneau, P., Simon, P., 2023. De la mixité des ascendances à l’hybridation des généalogies. *Documents de travail*, n°288, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://doi.org/10.48756/ined-dt-288.0124)

**Ferry, M.**, Simon, P., 2023. Les rapports aux origines : des identités mouvantes confrontées aux assignations. *Documents de travail*, n°287, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://archined.ined.fr/view/d5wI84wB-5e4nGnw6Kgw)

Caron, L., **Ferry, M.**, Ichou, M., 2023. Diversité sociale des immigré·es et de leurs enfants : positions et mobilité intergénérationnelle. *Documents de travail,* n°282, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://doi.org/10.48756/ined-dt-282.1123)

------------------------------------------------------------------------

Weber, R., **Ferry, M.**, & Ichou, M. (2023). Which Degree for Which Occupation? Vertical and Horizontal Mismatch Among Immigrants, Their Children, and Grandchildren in France., *Documents de travail Ined,* 278.

[{{< iconify icons8 pdf >}} PDF](https://archined.ined.fr/download/publication/E5OPhosBhU4QGwadVTE1/36fe6e5514cb19419c2bdf1cbc68b9d51699446278245.pdf) [{{< iconify gg website >}} Site web](https://archined.ined.fr/view/E5OPhosBhU4QGwadVTE1)

------------------------------------------------------------------------

**Ferry, M.**, & Subtil, J. (2023). Digitized Matchmaking. Marriage-making strategies of the New Middle Class through online matrimonial advertisements in India. *CSH-IFP Working Papers,* 19.

[{{< iconify icons8 pdf >}} PDF](https://mathieuferry.github.io/PondicherryWorkshop/material/wp/Digitized%20Matchmaking_WP19.pdf)

------------------------------------------------------------------------

**Ferry, M.** (2019). Les liens de la caste : Quantifier des identités sociales à l'aide de questions ouvertes. *Sciences Po OSC Papers,* 1.

[{{< iconify icons8 pdf >}} PDF](https://www.sciencespo.fr/osc/sites/sciencespo.fr.osc/files/OP_2019-1_FR_def.pdf) [{{< iconify gg website >}} Site web](https://www.sciencespo.fr/osc/fr/node/2089.html)
:::

------------------------------------------------------------------------
