---
title: ""
page-layout: full
---

::: {.content-visible when-profile="english"}
*The following three working papers compile several analyses to which I have contributed, drawing on the "Trajectoires & Origines 2" (TeO2) survey focused on immigrants and immigrants' descendants in metropolitan France. These papers are intended for publication as chapters in a book project that is presently under review:*

**Ferry, M.**, Tanneau, P., Simon, P., 2023. De la mixité des ascendances à l’hybridation des généalogies. *Documents de travail*, n°288, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://doi.org/10.48756/ined-dt-288.0124)

**Ferry, M.**, Simon, P., 2023. Les rapports aux origines : des identités mouvantes confrontées aux assignations. *Documents de travail*, n°287, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://archined.ined.fr/view/d5wI84wB-5e4nGnw6Kgw)

Caron, L., **Ferry, M.**, Ichou, M., 2023. Diversité sociale des immigré·es et de leurs enfants : positions et mobilité intergénérationnelle. *Documents de travail,* n°282, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://doi.org/10.48756/ined-dt-282.1123)

------------------------------------------------------------------------

Weber, R., **Ferry, M.**, Ichou, M., 2023. Which Degree for Which Occupation? Vertical and Horizontal Mismatch Among Immigrants, Their Children, and Grandchildren in France. *Documents de travail*, n°278, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://archined.ined.fr/view/E5OPhosBhU4QGwadVTE1)

------------------------------------------------------------------------

Al Dahdah, M., **Ferry, M.**, Guérin, I., & Venkatasubramanian, G. (2020). The Covid-19 Crisis in India. *Books & ideas*.

[{{< iconify gg website >}} Website](https://booksandideas.net/The-Covid-19-Crisis-in-India.html)

*Note: this article was also published in a shortened version in* [Public Books](https://www.publicbooks.org/india-in-covid-19-a-tragedy-foretold/).

------------------------------------------------------------------------

**Ferry M.** (2019). En Inde, des attaques contre les minorités au nom de la vache sacrée. *Bulletin de l'Observatoire international du religieux*, 31.

[{{< iconify gg website >}} Website](https://obsreligion.cnrs.fr/bulletin/en-inde-des-attaques-contre-les-minorites-au-nom-de-la-vache-sacree/)

------------------------------------------------------------------------

**Ferry, M.** (2018). Cow Terrorism. *Books & ideas*.

[{{< iconify gg website >}} Website](http://www.booksandideas.net/Cow-Terrorism.html)
:::

::: {.content-visible when-profile="french"}
*Les trois documents de travail suivants rassemblent plusieurs analyses auxquelles j'ai contribué, en se basant sur l'enquête "Trajectoires & Origines 2" (TeO2) portant sur les immigrants et leurs descendants en France métropolitaine. Ils sont destinés à être publiés en tant que chapitres d'un ouvrage actuellement en cours de révision :*

**Ferry, M.**, Tanneau, P., Simon, P., 2023. De la mixité des ascendances à l’hybridation des généalogies. *Documents de travail*, n°288, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://doi.org/10.48756/ined-dt-288.0124)

**Ferry, M.**, Simon, P., 2023. Les rapports aux origines : des identités mouvantes confrontées aux assignations. *Documents de travail*, n°287, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://archined.ined.fr/view/d5wI84wB-5e4nGnw6Kgw)

Caron, L., **Ferry, M.**, Ichou, M., 2023. Diversité sociale des immigré·es et de leurs enfants : positions et mobilité intergénérationnelle. *Documents de travail,* n°282, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://doi.org/10.48756/ined-dt-282.1123)

------------------------------------------------------------------------

Weber, R., **Ferry, M.**, Ichou, M., 2023. Which Degree for Which Occupation? Vertical and Horizontal Mismatch Among Immigrants, Their Children, and Grandchildren in France. *Documents de travail*, n°278, Aubervilliers : Ined.

[{{< iconify gg website >}} Website](https://archined.ined.fr/view/E5OPhosBhU4QGwadVTE1)

Al Dahdah, M., **Ferry, M.**, Guérin, I., & Venkatasubramanian, G. (2020). L'Inde face à la crise du Covid-19. *La Vie des idées*.

[{{< iconify gg website >}} Site web](https://laviedesidees.fr/L-Inde-face-a-la-crise-du-Covid-19.html)

------------------------------------------------------------------------

**Ferry M.** (2019). En Inde, des attaques contre les minorités au nom de la vache sacrée. *Bulletin de l'Observatoire international du religieux*, 31.

[{{< iconify gg website >}} Site web](https://obsreligion.cnrs.fr/bulletin/en-inde-des-attaques-contre-les-minorites-au-nom-de-la-vache-sacree/)

------------------------------------------------------------------------

**Ferry, M.** (2017). Le terrorisme de la vache. *La Vie des idées*.

[{{< iconify gg website >}} Site web](http://www.laviedesidees.fr/Le-terrorisme-de-la-vache.html)
:::
